### ISSUE TITLE
(new ui) `window is not defined` in useViewport

### ISSUE THREAD

**Issue by Dhravya** [supermemoryai/supermemory#3]
```
web:dev:  ⨯ src/hooks/useViewport.ts (4:53) @ window
web:dev:  ⨯ ReferenceError: window is not defined
web:dev:     at getViewport (./src/hooks/useViewport.ts:9:56)
web:dev:     at useViewport (./src/hooks/useViewport.ts:19:85)
web:dev:     at Main (./src/components/Main.tsx:25:85)
web:dev:   2 |
web:dev:   3 | function getViewport() {
web:dev: > 4 |   const { innerWidth: width, innerHeight: height } = window ?? {
web:dev:     |                                                     ^
web:dev:   5 |     innerWidth: 0,
web:dev:   6 |     innerHeight: 0,
web:dev:   7 |   };
web:dev:  ⨯ src/hooks/useViewport.ts (4:53) @ window
web:dev:  ⨯ ReferenceError: window is not defined
web:dev:     at getViewport (./src/hooks/useViewport.ts:9:56)
web:dev:     at useViewport (./src/hooks/useViewport.ts:19:85)
web:dev:     at Main (./src/components/Main.tsx:25:85)
web:dev:   2 |
web:dev:   3 | function getViewport() {
web:dev: > 4 |   const { innerWidth: width, innerHeight: height } = window ?? {
web:dev:     |                                                     ^
web:dev:   5 |     innerWidth: 0,
web:dev:   6 |     innerHeight: 0,
web:dev:   7 |   };
web:dev:  ⨯ src/hooks/useViewport.ts (4:53) @ window
web:dev:  ⨯ ReferenceError: window is not defined
web:dev:     at getViewport (./src/hooks/useViewport.ts:9:56)
web:dev:     at useViewport (./src/hooks/useViewport.ts:19:85)
web:dev:     at Main (./src/components/Main.tsx:25:85)
web:dev:   2 |
web:dev:   3 | function getViewport() {
web:dev: > 4 |   const { innerWidth: width, innerHeight: height } = window ?? {
web:dev:     |                                                     ^
web:dev:   5 |     innerWidth: 0,
web:dev:   6 |     innerHeight: 0,
web:dev:   7 |   };
```

**Comment by yxshv** [comment]
fixed
